name       : profanity
version    : 0.6.0
release    : 3
source     :
    - https://github.com/boothj5/profanity/releases/download/0.6.0/profanity-0.6.0.tar.gz : f1b2773b79eb294297686f3913e9489c20effae5e3a335c8956db18f6ee2f660
license    : GPL-3.0-or-later
component  : network.im
summary    : Profanity - A console based XMPP client
description: |
    Profanity is a console based XMPP client written in C using ncurses and libstrophe, inspired by Irssi.
    Feautres:
    - Supports XMPP chat services, including GoogleTalk
    - MUC chat room support
    - OTR and PGP encryption
    - Roster management
    - Flexible resource and priority settings
    - Desktop notifications
    - Plugins in Python and C
builddeps  :
    - pkgconfig(cmocka)     # check
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libotr)
    - pkgconfig(libstrophe)
    - pkgconfig(ncursesw)
    - pkgconfig(python3)
    - libgcrypt-devel
setup      : |
    %configure PYTHON_VERSION=%python3_version%
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
